# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-incubator/custom-metrics-apiserver"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  revision = "302974c03f7e50f16561ba237db776ab93594ef6"
  name = "k8s.io/apimachinery"

[[constraint]]
  version = "kubernetes-1.10.0"
  name = "k8s.io/apiserver"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[[constraint]]
  version = "kubernetes-1.10.0"
  name = "k8s.io/metrics"

[prune]
  go-tests = true
  unused-packages = true
