apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
  annotations:
    # custom-metrics.<metricType>.<metricName>.<metricFormat>/<config>
    custom-metrics.pods.packets-per-second.json-path/json-key: "json.path"
    custom-metrics.pods.packets-per-second.json-path/path: /metrics
    custom-metrics.pods.packets-per-second.json-path/port: "9090"
    custom-metrics.object.requests-per-second.prometheus/query: |
      sum(rate(apiserver_request_count{application="kube-apiserver"}[1m]))
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: custom-metrics-consumer
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Pods
    pods:
      metricName: packets-per-second
      targetAverageValue: 1k
  - type: Object
    object:
      metricName: requests-per-second
      target:
        apiVersion: extensions/v1beta1
        kind: Ingress
        name: main-route
      targetValue: 10k
